// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axdvjakhgjnebjwcsjdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4ZHZqYWtoZ2puZWJqd2NzamRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0NjE5MjgsImV4cCI6MjA1MDAzNzkyOH0.S564FkpelQg9s-HLd0jRiBhDkmy1uKLTkp2rOT6HfIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);